services:
  api:
    build:
      context: ./api
      args:
        - BUILD_TIME=${BUILD_TIME}
    env_file: .env
    environment:
      - PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    command: ["node", "dist/server.js"]

  # Web service scaffold reserved for the upcoming Next.js app.
  # Uncomment and implement once the web directory is populated.
  # web:
  #   build:
  #     context: ./web
  #   env_file: .env
  #   environment:
  #     - PORT=${WEB_PORT}
  #     - API_BASE_URL=http://api:${API_PORT}
  #   ports:
  #     - "${WEB_PORT}:${WEB_PORT}"
  #   depends_on:
  #     - api
  #   restart: unless-stopped

networks:
  default:
    name: fact-checker-net
